server:
  port: 9000
  servlet:
    session:
      timeout: 30m  # 세션 타임아웃을 30분으로 설정

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://database-2.czoko0kccb4t.ap-northeast-2.rds.amazonaws.com:3306/deliciousbee
    username: root
    password: gogoroot
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show-sql: true
        format-sql: true
  security:
    oauth2:
      client:
        registration:
          line:
            client-id: 2006326924
            client-secret: 23fd1eeaf3277c35d018a4058a03d2b8
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            scope:
              - profile
              - openid
              - email
            client-name: LINE
          google:
            client-id: 379634644088-1g4tgnt6n8d6rsvp3trb34mii0qdj7nv.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
        provider:
          line:
            authorization-uri: https://access.line.me/oauth2/v2.1/authorize
            token-uri: https://api.line.me/oauth2/v2.1/token
            user-info-uri: https://api.line.me/oauth2/v2.1/userinfo
            user-name-attribute: sub
            jwk-set-uri: https://api.line.me/oauth2/v2.1/certs
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
            user-name-attribute: sub
  logging:
    level:
      org.springframework.security.oauth2: DEBUG
      org.springframework.web: DEBUG
      org.springframework.security.authentication.AuthenticationManager: DEBUG

